bytecodealliance/go-modules

wit/codec.go
Do not depend on assignment evaluation order in multiple assignment where one RHS value mutates another RHS value.
=> Do not depend on undefined assignment order

.github/workflows/go.yaml, wit/abi.go, wit/abi_test.go, wit/resolve.go
Fixes u32 overflow in test:
```sh
$ tinygo test -target=wasi ./...
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.3
go: downloading github.com/mattn/go-isatty v0.0.20
?   	github.com/ydnar/wasm-tools-go/cmd/wit-bindgen-go	[no test files]
?   	github.com/ydnar/wasm-tools-go/cmd/wit-bindgen-go/cmd/print	[no test files]
?   	github.com/ydnar/wasm-tools-go/cmd/wit-bindgen-go/cmd/syntax	[no test files]
?   	github.com/ydnar/wasm-tools-go/internal/callerfs	[no test files]
?   	github.com/ydnar/wasm-tools-go/internal/codec	[no test files]
?   	github.com/ydnar/wasm-tools-go/internal/codec/json	[no test files]
?   	github.com/ydnar/wasm-tools-go/internal/witcli	[no test files]
FAIL	github.com/ydnar/wasm-tools-go/wit	0.000s
wit/abi_test.go:45:62: cannot use math.MaxUint32 (untyped int …
```
=> Fix Discriminant on 32-bit platforms

testdata/examples/resource-in-world.wit, testdata/examples/resource-in-world.wit.json, testdata/examples/resource-in-world.wit.json.golden, testdata/examples/resource-in-world.wit.json.golden.wit, testdata/wasi/clocks.wit.json.golden.wit, testdata/wit-parser/cross-package-resource.wit.json.golden.wit, testdata/wit-parser/name-both-resource-and-type.wit.json.golden.wit, testdata/wit-parser/resources-empty.wit.json.golden.wit, testdata/wit-parser/resources-multiple-returns-borrow.wit.json.golden.wit, testdata/wit-parser/resources-multiple-returns-own.wit.json.golden.wit, testdata/wit-parser/resources-multiple.wit.json.golden.wit, testdata/wit-parser/resources-return-borrow.wit.json.golden.wit, testdata/wit-parser/resources-return-own.wit.json.golden.wit, testdata/wit-parser/resources.wit.json.golden.wit, testdata/wit-parser/resources1.wit.json.golden.wit, testdata/wit-parser/types.wit.json.golden.wit, testdata/wit-parser/world-top-level-resources.wit.json.golden.wit, wit/abi.go, wit/docs.go, wit/resolve.go, wit/testdata_test.go, wit/wit.go
This PR improves support for Component Model resource types and own/borrow handles.
- `Resource` methods, constructor, and static functions can be reversed back into WIT form with `wasm-tools-go wit`
- `Result` types without an error value are `result<T>` and not `result<T, _>`
- Adds helper methods to `TypeDef`:
- `Constructor() *Function`
- `Methods() []*Function`
- `StaticFunctions() []*Function`
These are needed for WIT generation and will serve as a foundation for Go codegen.
=> WIT resource support

cm/layout_test.go
Align `want, got` order consistent with other tests.
=> cm: reorder want, got in tests

cmd/wit-bindgen-go/cmd/generate/generate.go, wit/bindgen/generator.go, wit/bindgen/options.go
This also changes the versioned path from <path>/v<version> to <path>-<version>.
This also preserves the kebab-case of a WIT interface or world into the Go package path.
=> option to generate versioned package paths by default

wit/resolve.go
This produces deterministic output from `wit-bindgen-go generate`.
=> wit: sort methods and statics by name

cmd/wit-bindgen-go/cmd/generate/generate.go, wit/bindgen/options.go
- **cmd/wit-bindgen-go/cmd/generate, wit/bindgen: remove ident mapping options**
- **cmd/wit-bindgen-go/cmd/generate: trim space**
- **cmd/wit-bindgen-go/cmd/generate: --package-root argument**
=> all: --package-root argument to allow binding generation in module std

wit/bindgen/generator.go
This makes Go imports slightly nicer, without trailing version number when used with --versioned. This corresponds with the WIT syntax that allows *packages* to be versioned, but not *interfaces* or *worlds*.
https://github.com/WebAssembly/wasi-io/blob/main/wit/streams.wit
Before:
```go
import streams "syscall/wasi/io/streams/v0.2.0"
```
After:
```go
import "syscall/wasi/io/v0.2.0/streams"
```
=> wit/bindgen: generate Go vN.N.N version directory beneath interface dir

testdata/wasi/cli.wit.json.golden.wit, testdata/wasi/http.wit.json.golden.wit, testdata/wit-parser/resources-empty.wit.json.golden.wit, testdata/wit-parser/resources-multiple-returns-own.wit.json.golden.wit, testdata/wit-parser/resources-multiple.wit.json.golden.wit, testdata/wit-parser/resources-return-own.wit.json.golden.wit, testdata/wit-parser/resources.wit.json.golden.wit, testdata/wit-parser/resources1.wit.json.golden.wit, testdata/wit-parser/world-top-level-resources.wit.json.golden.wit, wit/wit.go
- **wit: only emit own<T> handles in type alias statements**
- **testdata: only emit own<T> in type alias statements**
=> all: only emit own<T> in type alias statements

cmd/wit-bindgen-go/cmd/generate/generate.go, wit/bindgen/generator.go, wit/bindgen/options.go
This PR adds a `--world` argument to `wit-bindgen-go generate`, which limits Go code generation to a specific WIT world.
The argument may be a single name like `proxy` or a partially or fully-qualified WIT identifier:
- `proxy`
- `wasi:http/proxy`
- `wasi:http/proxy@0.2.0`
This mimics the behavior of `wit-bindgen`, with the caveat that `wit-bindgen-go` will generate Go bindings for *all* worlds in the resolved WIT by default.
Todo in future PR:
=> all: add --world argument to limit generating Go bindings to a specific WIT world

wit/bindgen/generator.go
For wasi:cli, this means it will generated wasi:cli/command world by default, with no -world argument specified.
=> wit/bindgen: generate last world by default, not all worlds

testdata/example/flat-variant.wit, testdata/example/flat-variant.wit.json, testdata/example/flat-variant.wit.json.golden.wit, wit/abi_test.go, wit/resolve.go
This correctly implements the Canonical ABI [flattening rules](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#flattening) for `variant`, `option`, and `result` types (which despecialize into `variant`). Namely overlapping types are replaced with either `uint32` or `uint64`, even if one of the overlapping types is a `float32` or `float64`.
Related to #97 and #98.
=> wit: align Canonical ABI flattening rules with the spec

testdata/wasi/cli.wit.json.golden.wit, testdata/wasi/http.wit.json.golden.wit, testdata/wit-parser/complex-include.wit.json.golden.wit, testdata/wit-parser/cross-package-resource.wit.json.golden.wit, testdata/wit-parser/diamond1.wit.json.golden.wit, testdata/wit-parser/empty.wit.json.golden.wit, testdata/wit-parser/foreign-deps-union.wit.json.golden.wit, testdata/wit-parser/foreign-deps.wit.json.golden.wit, testdata/wit-parser/ignore-files-deps.wit.json.golden.wit, testdata/wit-parser/kinds-of-deps.wit.json.golden.wit, testdata/wit-parser/multi-file-multi-package.wit.json.golden.wit, testdata/wit-parser/multi-package-shared-deps.wit.json.golden.wit, testdata/wit-parser/multi-package-transitive-deps.wit.json.golden.wit, testdata/wit-parser/name-both-resource-and-type.wit.json.golden.wit, testdata/wit-parser/package-syntax1.wit.json.golden.wit, testdata/wit-parser/package-syntax3.wit.json.golden.wit, testdata/wit-parser/package-syntax4.wit.json.golden.wit, testdata/wit-parser/packages-explicit-colliding-decl-names.wit.json.golden.wit, testdata/wit-parser/packages-explicit-internal-references.wit.json.golden.wit, testdata/wit-parser/packages-explicit-with-semver.wit.json.golden.wit, testdata/wit-parser/packages-multiple-explicit.wit.json.golden.wit, testdata/wit-parser/versions.wit.json.golden.wit, wit/testdata_test.go, wit/wit.go
This adds support for WIT files containing multiple packages. Implemented here in `wasm-tools`: https://github.com/bytecodealliance/wasm-tools/pull/1577
This depends on an unreleased version of `wasm-tools` that includes commit https://github.com/bytecodealliance/wasm-tools/commit/2728f93ab66edda25a865bc54b81f66f98ca344a.
=> wit: add support for WIT files with multiple packages

wit/bindgen/generator.go, wit/resolve.go, wit/wit.go
Type name (foo) and kind (u32) are distinct. Use `WITKind` when a kind is desired, and `TypeName` when a named type is required.
=> wit: split the function of type kind and name 

cmd/wit-bindgen-go/cmd/generate/generate.go, internal/go/gen/file.go, internal/go/gen/file_test.go, internal/go/gen/package.go, wit/bindgen/generator.go
- **internal/go: add File.HasContent**
- **cmd/wit-bindgen-go: skip writing Go files without content**
- **wit/bindgen: defer creating abi.go file until needed**
- **wit/bindgen: pass file, not ABI file to typeDefLowerFunction**
=> wit/bindgen: skip writing empty Go files

wit/abi.go, wit/bindgen/generator.go, wit/resolve.go
The implementation of post-return functions (`cabi_post_*`) was wrong. This PR does two things:
1. Correct the function signature of post-return functions, deriving from the flattened (Core WebAssembly) version of exported functions, rather than the original function signature.
2. Disable generation of Go `*PostReturn` functions, including user-defined side, until a point at which we can generate a correct implementation.
The implementation of post-return functions for Go needs more design work. Given that Go has a GC, the returned pointers should eventually be garbage collected. Areas of exploration:
- Create a bookkeeping mechanism to keep track of pointers passed to `wasmexport` functions and free/release them when passed back via a post-return function.
- Determine whether this should …
=> wit/bindgen: disable generation of post-return functions

.github/workflows/test.yaml
- **.github/workflows: bump wasm-tools crate to v1.212.0**
- **.github/workflows: use v(N) versions for GitHub Actions dependencies**
=> chore: bump dependencies

CHANGELOG.md, internal/go/gen/names.go, wit/bindgen/names.go, wit/bindgen/names_test.go
- **internal/go/gen: add OK as a known initialism**
- **wit/bindgen: preserve acronym/initialism UPPERCASE segments in WIT names**
=> wit/bindgen: preserve all-uppercase segments in WIT identifiers

CHANGELOG.md, cm/abi.go, cm/debug_test.go, cm/result.go, cm/result_test.go, cm/variant.go, testdata/example/only-result.wit, testdata/example/only-result.wit.json, testdata/example/only-result.wit.json.golden.wit, testdata/issues/issue95.wit, testdata/issues/issue95.wit.json, testdata/issues/issue95.wit.json.golden.wit, wit/bindgen/abi.go, wit/bindgen/generator.go, wit/resolve.go
This PR implements a change to how `result` and `variant` types are represented in Go, namely generating a storage shape sized to match the largest associated type.
1. It implements an experiment, enabled by default, to generate `byte` array backing for `result` and `variant` data fields. This makes the ergonomics of using generated code slightly worse, by introducing single-use types, e.g. `MyRecordShape` into caller-visible code.
2. It implemented, then reverted, a fix for the data shape of `result` and `variant` types using arrays. This fix, does not work with TinyGo (LLVM), so it was abandoned (see e9d6c260fc6167ba32ee546295f14b91d0fe2982).
This corrects an issue with the original implementation, which used a Go type parameter `Shape` in `Variant` and `*Result` types. If a variant …
=> all: use byte array shape for result and variant data

wit/bindgen/generator.go
this adds String() method for enum type as discussed in #127 
If this approach looks ok, I will also try to add for variant and flag types.
=> add mapping and String() method for enum type in generated bindings

.github/workflows/test.yaml, .gitignore, CHANGELOG.md, cm/abi.go, cm/docs.go, cm/tuple.go, design/README.md
This PR adds TinyGo 0.32.0 to test matrix, updates `wasm-tools` to latest, along with the following changes:
- `Tuple9`...`Tuple16` types in package `cm` to align with [component-model#373](https://github.com/WebAssembly/component-model/issues/373). Tuples with 9 to 16 types will no longer generate inline `struct` types.
- Documentation for Canonical ABI lift and lower helper functions in package `cm`.
- Removed outdated documentation in [design](./design/README.md).
=> all: cleanup

.github/workflows/test.yaml, cabi/realloc.go, internal/relpath/getwd_other.go, internal/relpath/getwd_wasip1.go, internal/relpath/relpath.go
This PR adds Go 1.23 and TinyGo 0.33 to the test matrix, with necessary workarounds to make it work.
=> chore: add Go 1.23 and TinyGo 0.33.0 to test matrix

.github/workflows/test.yaml, CHANGELOG.md, testdata/wasi/cli.wit.json.golden.wit, testdata/wasi/http.wit.json.golden.wit, testdata/wit-parser/complex-include.wit.json.golden.wit, testdata/wit-parser/cross-package-resource.wit.json.golden.wit, testdata/wit-parser/diamond1.wit.json.golden.wit, testdata/wit-parser/foreign-deps-union.wit.json.golden.wit, testdata/wit-parser/foreign-deps.wit.json.golden.wit, testdata/wit-parser/ignore-files-deps.wit.json.golden.wit, testdata/wit-parser/kinds-of-deps.wit.json.golden.wit, testdata/wit-parser/multi-file-multi-package.wit.json.golden.wit, testdata/wit-parser/multi-package-shared-deps.wit.json.golden.wit, testdata/wit-parser/multi-package-transitive-deps.wit.json.golden.wit, testdata/wit-parser/name-both-resource-and-type.wit.json.golden.wit, testdata/wit-parser/packages-explicit-colliding-decl-names.wit.json.golden.wit, testdata/wit-parser/packages-explicit-internal-references.wit.json.golden.wit, testdata/wit-parser/packages-explicit-with-semver.wit.json.golden.wit, testdata/wit-parser/packages-multiple-explicit.wit.json.golden.wit, testdata/wit-parser/versions.wit.json.golden.wit, wit/wit.go
- **wit: emit multi-package, single-file WIT with a top-level un-nested root package**
- **testdata: regenerate WIT with un-nested root package**
- **.github/workflows: update to wasm-tools@1.216.0**
- **CHANGELOG: update for multi-package, single-file WIT serialization**
=> wit: generate multi-package WIT files with an un-nested root package

CHANGELOG.md, cmd/wit-bindgen-go/main.go
The version and git revision are pulled from the debug.BuildMode struct.
Variation of #143.
=> cmd/wit-bindgen-go: add --version flag

testdata/issues/issue165.wit, testdata/issues/issue165.wit.json, testdata/issues/issue165.wit.json.golden.wit, wit/bindgen/generator.go
Fixes #165.
The real fix is probably to annotate type definitions in `wasm-tools` with direction (imported or exported).
=> wit/bindgen: propagate type direction to generated Go functions

CHANGELOG.md, testdata/issues/issue170.wit, testdata/issues/issue170.wit.json, testdata/issues/issue170.wit.json.golden.wit, wit/bindgen/generator.go, wit/resolve.go, wit/testdata_test.go
- **testdata/issues: add test case for #170**
- **wit: add Interface.InterfaceName() method**
=> wit, wit/bindgen: gracefully handle unnamed (yet named) interfaces in worlds. Fixes #170.

CHANGELOG.md, cm/hostlayout_go122.go, cm/hostlayout_go123.go, cm/hostlayout_test.go, cm/list.go, cm/option.go, cm/result.go, cm/result_test.go, cm/tuple.go, cm/tuple_test.go, cm/variant.go, testdata/example/non-flat-params.wit, testdata/example/non-flat-params.wit.json, testdata/example/non-flat-params.wit.json.golden.wit, wit/bindgen/generator.go, wit/bindgen/testdata_test.go
This implements a [`HostLayout`](https://github.com/golang/go/issues/66408) type in package `cm`, which is an alias for `structs.HostLayout` in Go 1.23 or later, and a polyfill for Go 1.22 or earlier.
It adds a zero-width `HostLayout` field to each generated struct to align with the [relaxed wasm types proposal](https://github.com/golang/go/issues/66984).
=> cm, wit/bindgen: add HostLayout field to generated structs

CHANGELOG.md, testdata/issues/issue175.wit, testdata/issues/issue175.wit.json, testdata/issues/issue175.wit.json.golden.wit, wit/bindgen/generator.go, wit/bindgen/testdata_test.go, wit/resolve.go, wit/testdata_test.go, wit/wit.go
Functions and interfaces imported into or exported directly from a world will now have the correct module name (`$root`).
For interfaces nested under a world, the generated Go package will be nested under the world’s package, e.g.:
```wit
package issues:issue175;
world w {
export example: interface {
f1: func() -> s32;
}
import f2: func() -> f32;
export f3: func() -> s64;
}
```
Creates two Go packages:
1. `issues/issue175/w` exporting or importing functions with module `$root`
2. `issues/issue175/w/example` exporting or importing functions with module `example`
Fixes #175.
=> wit, wit/bindgen: correctly generate linker names for world-level functions and interfaces

CHANGELOG.md, cm/abi.go, cm/list.go, cm/option.go, cm/result.go, cm/variant.go
- **cm: include HostLayout everywhere; add AnyList, AnyResult, and AnyVariant type constraints**
- **cm: use Result instead of equivalent struct**
=> cm: use HostLayout in all structs

.github/workflows/release.yaml, CHANGELOG.md, scripts/extract-changelog.sh
the release workflow will be triggered when a new tag is pushed to the remote, and will build, test and release the wit-bindgen-go binaries to the GitHub release page. It runs on linux, macos and windows and on amd64, arm64 architectures.
the built binary name is named as `wit-bindgen-go-<os>-<arch>`.
=> .github/workflows/release: add a release GitHub Action workflow

CHANGELOG.md, cm/option.go, cm/option_test.go, testdata/codegen/allow-unused.wit, testdata/codegen/allow-unused.wit.json, testdata/codegen/allow-unused.wit.json.golden.wit, wit/bindgen/generator.go
- **wit/bindgen: generate String() method for variant types**
- **cm: add Option.Value() method**
=> wit/bindgen, cm: add String() method to variant types; Value() method to option types

CHANGELOG.md, cm/abi.go, cm/list.go
`uint` was removed from the list of permitted types in https://github.com/golang/go/issues/66984.
- `cm.List` now stores list length as a `uintptr`, permitted by the [Go wasm types proposal](https://github.com/golang/go/issues/66984). It was previously a `uint`, which was removed from the list of permitted types. There should be no change in the memory layout in TinyGo `GOARCH=wasm` or Go `GOARCH=wasm32` using 32-bit pointers.
- The helper functions `cm.NewList`, `cm.LiftList`, and `cm.LiftString` now accept any integer type for `len`, defined as `cm.AnyInteger`.
=> cm: change list<T> len field to uintptr

CHANGELOG.md, testdata/example/aliases.wit, testdata/example/aliases.wit.json, testdata/example/aliases.wit.json.golden.wit, wit/bindgen/generator.go, wit/resolve.go, wit/wit.go
Go [type aliases](https://go.dev/ref/spec#Alias_declarations) are now generated for each WIT type alias (`type foo = bar`). Deep chains of type aliases (`type b = a; type c = b;`) are fully supported. Generated documentation now reflects whether a type is an alias.
For example, given the following WIT:
```wit
package example:aliases;
interface i {
resource r {
m: func() -> u32;
}
type a = r;
type b = a;
type c = b;
fa: func(v: a);
fb: func(v: b);
fc: func(v: c);
}
world w {
import i;
export i;
}
```
Generates the following Go:
```go
// R represents the imported resource "example:aliases/i#r".
//
//	resource r
type R cm.Resource
// A represents the imported type alias "example:aliases/i#a".
//
// See [R] for more information.
type A = R
// B represents the imported type alias …
```
=> wit, wit/bindgen: generate Go type aliases for WIT type aliases

CHANGELOG.md, Makefile, wit/bindgen/generator.go
This fixes two subtle bugs where creating a shape type for `result` or `variant` types used in a `wasmimport` function could have a side-effect of importing an unused Go package into the `.wasm.go` file, which would cause the generated Go to fail.
It should be reviewed commit by commit.
This is a follow up to #194.
=> wit/bindgen: tidy up .wasm.go file generation

CHANGELOG.md, internal/go/gen/package.go, wit/bindgen/generator.go, wit/bindgen/testdata_test.go
This is a step towards embedding textual WIT in a WebAssembly module generated by TinyGo (and eventually Go), for consumption by downstream programs like `wasm-tools` or for use as runtime metadata.
This can be verified by running `go test ./wit/bindgen -write` and examining the contents of the `generated` directory.
Inspired by #179.
=> wit/bindgen: generate pruned WIT file for each WIT world in the relevant Go package directory

CHANGELOG.md, testdata/issues/issue215.wit, testdata/issues/issue215.wit.json, testdata/issues/issue215.wit.json.golden.wit, wit/bindgen/generator.go
=> wit/bindgen: correctly scope generated variant accessor methods

.github/workflows/test.yaml
TinyGo 0.34.0 was released on October 26, 2024. This PR adds 0.34.0 to the testing matrix.
=> .github/workflows: test with TinyGo 0.34.0

cmd/wit-bindgen-go/main_test.go
This PR introduces a `verbose` flag to the `wit-bindgen-go` command line tool, along with a test that ensures it works properly in a simple case.
Resolves #212
=> cmd/wit-bindgen-go: add tests for verbose flag

CHANGELOG.md, testdata/issues/issue240.wit, testdata/issues/issue240.wit.json, testdata/issues/issue240.wit.json.golden.wit, testdata/issues/issue242.wit, testdata/issues/issue242.wit.json, testdata/issues/issue242.wit.json.golden.wit, tests/generated/wasi/filesystem/v0.2.0/types/abi.go, tests/generated/wasi/sockets/v0.2.0/tcp/abi.go, tests/generated/wasi/sockets/v0.2.0/udp/abi.go, wit/bindgen/generator.go
Correctly generate variant lowering code when a `variant` depends on a `resource`, and the `resource` depends on the `variant`.
Fixes #240 and #242.
=> wit/bindgen: correctly handle cyclical type dependencies

CHANGELOG.md, testdata/issues/issue264.wit, testdata/issues/issue264.wit.json, testdata/issues/issue264.wit.json.golden.wit, tests/generated/wasi/cli/v0.2.0/exit/exit.wit.go, tests/generated/wasi/cli/v0.2.0/run/run.wasm.go, tests/generated/wasi/filesystem/v0.2.0/types/types.wit.go, tests/generated/wasi/io/v0.2.0/poll/poll.wit.go, tests/generated/wasi/sockets/v0.2.0/tcp/tcp.wit.go, wit/bindgen/generator.go
Fixes #264.
- **testdata/issues: add example for #264**
- **wit/bindgen: ensure primtives are cast to correct Go types**
- **tests/generated/wasi: regenerate**
=> wit/bindgen: correctly cast to named Go bool types when lowering

CHANGELOG.md, cm/error.go, cm/error.wasm.go
- **CHANGELOG: move async types to Added section**
- **cm: follow pattern of generated wasmimport calls**
=> cm: use consistent pattern for wasmimport functions

tests/generated/wasi/clocks/v0.2.0/wall-clock/wall-clock.wit.go, tests/generated/wasi/filesystem/v0.2.0/types/types.wit.go, tests/generated/wasi/sockets/v0.2.0/network/network.wit.go, tests/generated/wasi/sockets/v0.2.0/udp/udp.wit.go, wit/bindgen/generator.go
Related to #239 
`HostLayout` receives `json:"-"` and any other field receives the original wit name.
```
// DateTime represents the record "wasi:clocks/wall-clock@0.2.0#datetime".
//
// A time and date in seconds plus nanoseconds.
//
//	record datetime {
//		seconds: u64,
//		nanoseconds: u32,
//	}
type DateTime struct {
_           cm.HostLayout `json:"-"`
Seconds     uint64        `json:"seconds"`
Nanoseconds uint32        `json:"nanoseconds"`
}
```
=> wit/bindgen: Add JSON tag to Record structs

.github/workflows/test.yaml, cm/CHANGELOG.md, cm/list.go, cm/list_test.go, cm/result_test.go
=> cm: implement JSON [un]marshaling for List types

CHANGELOG.md, testdata/issues/issue281.wit, testdata/issues/issue281.wit.json, testdata/issues/issue281.wit.json.golden.wit, wit/bindgen/generator.go, wit/bindgen/testdata_test.go, wit/ident.go, wit/ident_test.go, wit/wit.go
Errors from `wasm-tools` were being silently swallowed, masking a number of related issues:
1. WIT keywords in qualified interface or package names (like `import foo:foo/flags` were not being escaped (`foo:foo/%flags`).
2. Errors from `wasm-tools` invocations (in wasm) were being silently ignored. They are now logged and returned. Errors returned from `wasm-tools component embed` are now fatal.
3. Testdata tests in package `wit/bindgen` now supply a logger to `Go()`.
The synthetic world now uses the original WIT package, to allow inline `import foo: interface { ... }` with inline `use` statements that refer to other interfaces or worlds in the same package.
Fixes #281.
=> wit/bindgen: fix wasm-tools WIT generation bugs

CHANGELOG.md, wit/bindgen/generator.go, wit/list.go, wit/list_test.go
- **wit: change the ABI alignment of list<T> from 8 to 4**
- **wit/bindgen: call v.Types() once**
- **CHANGELOG: add note about #288**
=> wit: fix ABI alignment of list<T> to 4

CHANGELOG.md, testdata/issues/issue306.wit, testdata/issues/issue306.wit.json, testdata/issues/issue306.wit.json.golden.wit, wit/bindgen/generator.go
- **testdata/issues: add fixture for #306**
- **wit/bindgen: run wasm-tools with --all-features**
Fixes #306.
=> wit/bindgen: always run wasm-tools with --all-features

wit/bindgen/generator.go, wit/load.go
Emit stderr for non-zero exit code to make errors consistent between load and generate.
=> wit, wit/bindgen: improve wasm-tools error reporting

CHANGELOG.md, testdata/issues/issue306.wit, testdata/issues/issue306.wit.json, testdata/issues/issue306.wit.json.golden.wit, wit/bindgen/generator.go, wit/wit.go
Fixes #306. See https://github.com/bytecodealliance/go-modules/issues/306#issuecomment-2737873621.
=> wit, wit/bindgen: do not emit incompatible feature gates when generating WIT

cm/error.go, cm/error.wasm.go
[wadge](https://github.com/wasmCloud/wadge) ( Test Harness generator ) scans all generated code and no longer works with cm package version 2.x.
code generated via wit-bindgen-go uses Public Types for wasmimport/export functions.
The newly introduced `ErrorContext` in `cm` uses a private type ( `errorContext` ), making it impossible to shim it with `go:linkname`.
```
./bindings.wadge_test.go:24:78: name errorContext not exported by package cm
./bindings.wadge_test.go:44:70: name errorContext not exported by package cm
FAIL	github.com/wasmCloud/go/examples/component/http-server [build failed]
```
what wadge generates after parsing wit generated code:
=> cm: Use public type for errorContext wasm functions

Makefile, cm/CHANGELOG.md, cm/option.go, cm/result.go, cm/result_test.go, testdata/issues/issue344.wit, testdata/issues/issue344.wit.json, testdata/issues/issue344.wit.json.golden.wit, tests/generated/wasi/cli/v0.2.0/exit/exit.wit.go, tests/generated/wasi/cli/v0.2.0/run/run.wasm.go, wit/bindgen/generator.go
This PR implements a breaking change: `BoolResult` is now a `uint8` instead of `bool`, due to how LLVM represents a boolean value as a single bit, ignoring the high 7 bits. This breaks variants and other tagged unions if a `bool` is used as the memory shape.
Fixes #344.
=> cm: do not use bool discriminant in variant, result, and option types

.github/workflows/release.yaml
Closes https://github.com/bytecodealliance/go-modules/issues/345.
The statically-linked binary is actually smaller (on x86_64-linux at least) by about 60kb.
=> Build statically-linked pre-built binaries

CHANGELOG.md, cm/result_test.go, wit/abi.go, wit/abi_test.go, wit/enum.go, wit/flags.go, wit/future.go, wit/list.go, wit/option.go, wit/pointer.go, wit/record.go, wit/resource.go, wit/result.go, wit/stream.go, wit/tuple.go, wit/variant.go
Fixes #350.
See https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#element-size
=> wit: align record size to max field alignment

CHANGELOG.md, testdata/issues/issue352.wit, testdata/issues/issue352.wit.json, testdata/issues/issue352.wit.json.golden.wit, tests/generated/wasi/sockets/v0.2.0/network/abi.go, tests/generated/wasi/sockets/v0.2.0/network/network.wit.go, wit/bindgen/generator.go
=> wit/bindgen: create custom shape types for tuples
